language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - libusb-0.1-4

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest
  - bash test/test_cli.sh
